# Generated by flatpak-dev. Customize flatpak/.profile instead.
{{range $name, $value := .Environment -}}
export {{$name}}={{$value | shellQuote}};
{{end -}}
export BASH_ENV={{.ProfilePath | shellQuote}};
cd "$FLATPAK_DEV_PROJECT_ROOT" || return;
if [ -f "$FLATPAK_DEV_PROJECT_ROOT/flatpak/.profile" ]; then
  . "$FLATPAK_DEV_PROJECT_ROOT/flatpak/.profile" || return;
fi
